version: '3.9'

services:
  lab-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-lab-v1
    env_file:
      - .env.prod
    ports:
      - "3001:3001"
    networks:
      - backend
    volumes:
      - ./logs_host:/logs

networks:
  backend:
    driver: bridge
