services:
  lab-service:
    image: api-1-lab-service
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api-lab-v1-dev
    env_file:
      - .env.local
    ports:
      - "3001:3001"
    networks:
      - backend
    volumes:
      - ./app:/app
      - ./logs_host:/logs
    command: uvicorn main:app --host 0.0.0.0 --port 3001 --reload --reload-dir /app

networks:
  backend:
    driver: bridge
