services:
  lab-service:
    build: .
    container_name: api-lab-v1
    ports:
      - "3001:3001"
    env_file:
      - .env.local
    networks:
      - backend
    volumes:
      - ./logs_host:/logs

networks:
  backend:
    driver: bridge
